/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/Charts/BarChart.vue')['default']
    ConfirmModal: typeof import('./components/Common/ConfirmModal.vue')['default']
    HeaderBar: typeof import('./components/Layout/HeaderBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImagePreview: typeof import('./components/Common/ImagePreview.vue')['default']
    LineChart: typeof import('./components/Charts/LineChart.vue')['default']
    MainLayout: typeof import('./components/Layout/MainLayout.vue')['default']
    PageHeader: typeof import('./components/Common/PageHeader.vue')['default']
    PieChart: typeof import('./components/Charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/Common/SearchBar.vue')['default']
    Sidebar: typeof import('./components/Layout/Sidebar.vue')['default']
  }
}
